### ISSUE TITLE
Temperatures shown as stale if CoolingPump is not enabled

### ISSUE THREAD

**Issue by mjuhanne** [openvehicles/Open-Vehicle-iOS#25]
If CoolingPump in car_doors3_t struct is not set, all temperatures (except for tires) are shown as stale. However this should not be a general assumption.

Is this some kind of special case with Tesla Roadster or other car? Maybe remove the CoolingPump check from iOS app and move the logic to the specific OVMS3 Vehicle class?

I'm now updating the app, so I can make modifications there, but when it comes to vehicle specific logic, I don't know where they are required.

**Comment by markwj** [comment]
The code was there to support compatibility with the older protocol (where the stale ambient and pem flag was not there). Modern firmware should not need this, so I think it is safe to remove and just use the stale flags.

Implemented in [master f6a6cb4]
