### ISSUE TITLE
ovms.dexters-web.de server not supported

### ISSUE THREAD

**Issue by glynhudson** [openvehicles/Open-Vehicle-iOS#27]
The iOS seems to be hard-coded to api.openvehicles.com, the docs suggest EU OVMS users should use ovms.dexters-web.de server but the iOS app does not have an option to set the server. 

Ideally the server would be a dropdown box selection between api.openvehicles.com and V with the option for the user to add a custom OVMS server if required.

**Comment by gbonadio** [comment]
Yes you can change the server in the iPhone settings-> open vehicule -> ovms server

**Comment by glynhudson** [comment]
Ah, thanks! Your totally right, sorry I'm a dumb Android user. I never though to check in the system settings menu for the app settings, not exactly intuitive but not a fault of OVMS. Thanks again, this is what the settings menu looks like in a ipad: 

![IMG_0145](https://user-images.githubusercontent.com/758844/63657963-bbbd0d00-c79e-11e9-8bc8-574ec0ca7fa9.PNG)
