### ISSUE TITLE
Push notification registration

### ISSUE THREAD

**Issue by markwj** [openvehicles/Open-Vehicle-iOS#35]
A user is reporting that he cannot receive push notifications with the latest version of the App. It seems the notification registration is messed up when running iOS 13.

**Comment by SirSheik** [comment]
Thx markwj  
This is the information about my system:
- Version of OVMS module: v3
- Version of firmware: 3.2.005-42 (main)
- iOS app version: 1.8.1
- iOS version: 13.1.3 
I think it may be only with the latest version of the app, with the previous version the notifications worked correctly in iOS 13.

If you need more information or try something just tell me
Regards

**Comment by jheredianet** [comment]
Hi guys, I confirm that I'm using the same versions both on iOS and OVMS and notifications are not working.

**Comment by SirSheik** [comment]
Hello
Would it be possible to remove this latest version (1.8.1) from the App Store until the problem will solve?
With version 1.7.2 the only fault was the visualization of the percentage of battery, but the notifications worked.
Thx

**Comment by jheredianet** [comment]
Any news about that? As @SirSheik says, is it possible to rollback to a previos version until push notifications works again?

**Comment by markwj** [comment]
We can't roll back in the Apple App Store. No such functionality.

I have made a fix to this (to try to support both the old pre-IOS13 way, as well as the new IOS13 way), and it will be v1.8.2. It is in Apple's first stage approval process now. If that is ok, I will send to test flight beta testing this weekend. I will also provide a link here, you can use to join the beta testing.

Assuming no problems are found, it will be released after Apple's approval (probably mid next week).

**Comment by markwj** [comment]
This is resolved in v1.8.2.

**Comment by SirSheik** [comment]
Thank you.
The notifications work again but all notifications are received duplicates.
I attach a screenshot, but it also happens with other events.

![iOS Notification](https://user-images.githubusercontent.com/31892065/72076432-cf07e980-32f5-11ea-81a3-19f847b9ace6.png)
