### ISSUE TITLE
Car map images squashed

### ISSUE THREAD

**Issue by glynhudson** [openvehicles/Open-Vehicle-iOS#42]
I've noticed that most car map images (apart from roadster, Twizy, eNiro) look squashed on the map. The reason for this seems to be he iOS app expects a 96 x 96 square image while most car map images are rectangular e.g 48 x 96. 

There are two possible solutions to this:
- resize all the rectangular map images with clear space padding to be 96 x 96
or
-  Adjust the iOS app to handle different sized rectangular map images

![IMG_0157](https://user-images.githubusercontent.com/758844/94218316-22e64d00-fedc-11ea-9967-d313ab0e8980.jpg)

**Comment by markwj** [comment]
It does look cute ;-)

The car map images should be 96x96. I think it was originally done that way to allow easy rotation.

**Comment by markwj** [comment]
These ones are wrong:

> map_car_env200_white.png:                     PNG image data, 48 x 96, 8-bit/color RGBA, non-interlaced
> map_car_imiev_black.png:                      PNG image data, 65 x 128, 8-bit/color RGBA, non-interlaced
> map_car_imiev_blue.png:                       PNG image data, 65 x 128, 8-bit/color RGBA, non-interlaced
> map_car_imiev_cherrybrown.png:                PNG image data, 65 x 128, 8-bit/color RGBA, non-interlaced
> map_car_imiev_coolsilver.png:                 PNG image data, 65 x 128, 8-bit/color RGBA, non-interlaced
> map_car_imiev_white.png:                      PNG image data, 65 x 128, 8-bit/color RGBA, non-interlaced
> map_car_imiev_whitered.png:                   PNG image data, 65 x 128, 8-bit/color RGBA, non-interlaced
> map_car_kiasoul_cherryblackinfernored.png:    PNG image data, 33 x 64, 8-bit/color RGBA, non-interlaced
> map_car_kiasoul_clearwhite.png:               PNG image data, 33 x 64, 8-bit/color RGBA, non-interlaced
> map_car_kiasoul_pearlwhiteelectronicblue.png: PNG image data, 33 x 64, 8-bit/color RGBA, non-interlaced
> map_car_kiasoul_titaniumsilver.png:           PNG image data, 33 x 64, 8-bit/color RGBA, non-interlaced
> map_car_kona_blue.png:                        PNG image data, 67 x 128, 8-bit/color RGBA, non-interlaced
> map_car_kona_grey.png:                        PNG image data, 67 x 128, 8-bit/color RGBA, non-interlaced
> map_car_kona_red.png:                         PNG image data, 67 x 128, 8-bit/color RGBA, non-interlaced
> map_car_kona_white.png:                       PNG image data, 67 x 128, 8-bit/color RGBA, non-interlaced
> map_car_kona_yellow.png:                      PNG image data, 67 x 128, 8-bit/color RGBA, non-interlaced
> map_car_leaf_coulisred.png:                   PNG image data, 48 x 96, 8-bit/color RGBA, non-interlaced
> map_car_leaf_deepblue.png:                    PNG image data, 48 x 96, 8-bit/color RGBA, non-interlaced
> map_car_leaf_forgedbronze.png:                PNG image data, 48 x 96, 8-bit/color RGBA, non-interlaced
> map_car_leaf_gunmetallic.png:                 PNG image data, 48 x 96, 8-bit gray+alpha, non-interlaced
> map_car_leaf_pearlwhite.png:                  PNG image data, 48 x 96, 8-bit/color RGBA, non-interlaced
> map_car_leaf_superblack.png:                  PNG image data, 48 x 96, 8-bit gray+alpha, non-interlaced
> map_car_mgzs_black.png:                       PNG image data, 50 x 100, 8-bit colormap, non-interlaced
> map_car_mgzs_blue.png:                        PNG image data, 50 x 100, 8-bit colormap, non-interlaced
> map_car_mgzs_lightblue.png:                   PNG image data, 50 x 100, 8-bit colormap, non-interlaced
> map_car_mgzs_red.png:                         PNG image data, 50 x 100, 8-bit colormap, non-interlaced
> map_car_mgzs_white.png:                       PNG image data, 50 x 100, 8-bit colormap, non-interlaced
> map_car_twizy_diamondblackwithivygreen.png:   PNG image data, 48 x 96, 8-bit/color RGBA, non-interlaced
> map_car_twizy_snowwhiteandflameorange.png:    PNG image data, 48 x 96, 8-bit/color RGBA, non-interlaced
> map_car_twizy_snowwhiteandurbanblue.png:      PNG image data, 48 x 96, 8-bit/color RGBA, non-interlaced
> map_car_twizy_snowwhitewithblack.png:         PNG image data, 48 x 96, 8-bit/color RGBA, non-interlaced
> map_car_vwup_black.png:                       PNG image data, 49 x 96, 8-bit/color RGBA, non-interlaced
> map_car_vwup_blue.png:                        PNG image data, 49 x 96, 8-bit/color RGBA, non-interlaced
> map_car_vwup_red.png:                         PNG image data, 49 x 96, 8-bit/color RGBA, non-interlaced
> map_car_vwup_silver.png:                      PNG image data, 49 x 96, 8-bit/color RGBA, non-interlaced
> map_car_vwup_white.png:                       PNG image data, 49 x 96, 8-bit/color RGBA, non-interlaced
> map_car_vwup_yellow.png:                      PNG image data, 49 x 96, 8-bit/color RGBA, non-interlaced

**Comment by glynhudson** [comment]
I've been like this for most cars for a long time, I think users must just have got used to the short car look! 

Have you any idea how the padding to 96x96 could be automated? It will be a very arduous task to do each one individually!

**Comment by glynhudson** [comment]
Ok, I've submitted a PR to make the images square. If anyone needs to do this in the future I wrote s simple bash script using imagemagick convert to convert all the files in a folder to 96x96 and save the new files to a folder called `/square`:


```
mkdir square
for f in *.png
do
	echo "processing $f"
	convert -background none -gravity center $f -resize 96x96 -extent 96x96 square/$f
done
```
