### ISSUE TITLE
iOS App Not Connecting via URL (Self Hosted Server)

### ISSUE THREAD

**Issue by nilsmau** [openvehicles/Open-Vehicle-iOS#56]
I am trying to get the iOS App to connect to my self hosted server. 

**What works:** 
iOS App: Connecting **in LAN via LAN IP** & port 6867
Browser: in LAN via LAN IP & port 6867 (connection will be closed by the OVMS Server, that is okay)
Browser: via URL ovms.home.*******.de Port 80 -> Nginx Reverse Proxy -> LAN IP & port 6867 (connection will be closed by the OVMS Server, that is okay)
via URL, the Nginx reverse proxy shows something in the logs, for all three cases I can see logs in ovms_server.pl output, for both ways trying to access (obviously that is not foreseen) by browser ovms logs show

```
2024-11-26 18:10:40.918838 +0000 info  OVMS::Server::Core: #8 - - ConnStart
2024-11-26 18:10:40.919109 +0000 info  OVMS::Server::Core: #8 - - ConnFinish
```

**What does not work:**
iOS App: via **URL ovms.home.*******.de Port 80 -> Nginx Reverse Proxy -> LAN IP & port 6867**
in this case, neither the Nginx do show ANY connection nor does the OVMS Server print something. As it seems to me, the App just does not connect.
The total length of the url is 30 character (excl. http:// or https://)

Any advice would be appreciated... I would like connect via iOS App to my own server instance via the public URL to be able to connect on the go.

Thanks!

**Comment by markwj** [comment]
The OVMS protocol v2 is NOT HTTP traffic, so I doubt whether your NGINX reverse HTTP proxy will support forwarding it. You should just forward the traffic to it via normal Destination NAT.

**Comment by nilsmau** [comment]
@markwj, thank you! i must have not understood the config properly. I have managed to connect now (taking nginx proxy manager out of the game).
Solution: directly connecting to port 6867 from outside (opening that port as TCP in the local router and pointing it to the ovms server IP with the same port).
